#pragma config(Sensor, dgtl1,  ,               sensorQuadEncoder)
#pragma config(Motor,  port1,           LeftMotor,     tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port2,           RightMotor,    tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port3,           ArmMotor,      tmotorVex393, openLoop)
#pragma config(Motor,  port4,           EndeffectorMotor, tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	float speedMultiplier;
	float drivePowerX;
	float drivePowerY;

	float armPower;

	while(true)
	{
		if(vexRT[Btn6U] == 1)
		{
			speedMultiplier = 1.0;
		}
		else
		{
			speedMultiplier = 0.6;
		}

		drivePowerX = vexRT[Ch1];
		drivePowerY = vexRT[Ch2];

		motor[LeftMotor] = speedMultiplier*((drivePowerY + drivePowerX)/2);
		motor[RightMotor] = speedMultiplier*((drivePowerY - drivePowerX)/2);

		armPower = 0.6*vexRT[Ch2Xmtr2];

		motor[ArmMotor] = armPower;
	}
}
