#pragma config(Sensor, dgtl1,  HighLimitSwitch, sensorTouch)
#pragma config(Sensor, dgtl2,  LowLimitSwitch, sensorTouch)
#pragma config(Sensor, dgtl3,  EndeffectorLimitSwitch, sensorTouch)
#pragma config(Motor,  port1,           LeftMotor,     tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port2,           RightMotor,    tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port3,           ArmMotor,      tmotorVex393, openLoop)
#pragma config(Motor,  port4,           EndeffectorMotor, tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	float speedMultiplier;
	float drivePowerX;
	float drivePowerY;

	float armPower;
	bool armPosition = false;

	float endEffectorPower;

	while(true)
	{
		if(vexRT[Btn6U] == 1)
		{
			speedMultiplier = 1.0;
		}
		else
		{
			speedMultiplier = 0.6;
		}

		drivePowerX = vexRT[Ch1];
		drivePowerY = vexRT[Ch2];

		motor[LeftMotor] = speedMultiplier*((drivePowerY + drivePowerX)/2);
		motor[RightMotor] = speedMultiplier*((drivePowerY - drivePowerX)/2);

		/*if(vexRT[Btn6UXmtr2] == 1 && armPosition)
		{
			armPower = -.6;
			if(SensorValue(LowLimitSwitch) == 1)
			{
			armPosition = false;
			}
		}
		else if(vexRTBtn6UXmtr2] == 1 && !armPosition)
		{
			armPower = .6;
			if(SensorValue(HighLimitSwitch) == 1)
			{
			armPosition = true;
			}
		}
		else
		{
			armPower = 0
		}*/

		if(vexRT[BtnXmrt6D] == 1)
		{
			armPower = 0.6*vexRT[Ch2Xmtr2];
		}
		motor[ArmMotor] = armPower;

		//Sensor test code
		if(SensorValue(EndeffectorLimitSwitch) == 1)
		{
			motor[LeftMotor] = .6;
		}
	}
}
