#pragma config(Sensor, dgtl1,  HighLimitSwitch, sensorTouch)
#pragma config(Sensor, dgtl2,  LowLimitSwitch, sensorTouch)
#pragma config(Sensor, dgtl3,  EndeffectorLimitSwitch, sensorTouch)
#pragma config(Motor,  port2,           RightMotor,    tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port3,           LeftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           ArmMotor,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           RightEndeffectorMotor, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           LeftEndeffectorMotor, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	float speedMultiplier;
	float drivePowerX;
	float drivePowerY;

	float armPower;
	float armMultiplier = .8;

	float endEffectorPower;
	float endEffectorMultiplier = 1;

	while(true)
	{
		if(vexRT[Btn6U] == 1)
		{
			speedMultiplier = 1.0;
		}
		else
		{
			speedMultiplier = 0.7;
		}

		drivePowerX = vexRT[Ch1];
		drivePowerY = vexRT[Ch2];

		motor[LeftMotor] = speedMultiplier*((drivePowerY + drivePowerX)/2);
		motor[RightMotor] = speedMultiplier*((drivePowerY - drivePowerX)/2);

		//Operator controls
		//Arm
		if(vexRT[Btn6UXmtr2] == 1)
		{
			armPower = vexRT[Ch2Xmtr2];
		}
		else
		{
			armPower = 0;
		}

		motor[ArmMotor] = armMultiplier*armPower;

		//Conveyor
		if(vexRT[Btn5UXmtr2] == 1)
		{
			endEffectorPower = 127;
		}
		else if(vexRT[Btn5DXmtr2] == 1)
		{
			endEffectorPower = -127;
		}
		else
		{
			endEffectorPower = 0;
		}

		motor[LeftEndeffectorMotor] = endEffectorMultiplier*endEffectorPower;
		motor[RightEndeffectorMotor] = endEffectorMultiplier*endEffectorPower;

		/*if(vexRT[Btn6UXmtr2] == 1 && armPosition)
		{
			armPower = -.6;
			if(SensorValue(LowLimitSwitch) == 1)
			{
			armPosition = false;
			}
		}
		else if(vexRTBtn6UXmtr2] == 1 && !armPosition)
		{
			armPower = .6;
			if(SensorValue(HighLimitSwitch) == 1)
			{
			armPosition = true;
			}
		}
		else
		{
			armPower = 0
		}*/
	}
}
